version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge