version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge