version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge