version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: my-portfolio
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge