services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - portfolio-network

  backend:
    build: ./backend
    environment:
      - ENVIRONMENT=production
    expose:
      - "8000"
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge